/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* DMA_INTERRUPT */
#define DMA_INTERRUPT__INTC_CORTEXM4_ASSIGNED 1
#define DMA_INTERRUPT__INTC_CORTEXM4_PRIORITY 7u
#define DMA_INTERRUPT__INTC_NUMBER 122u
#define DMA_INTERRUPT_INTC_CORTEXM4_ASSIGNED 1
#define DMA_INTERRUPT_INTC_CORTEXM4_PRIORITY 7u
#define DMA_INTERRUPT_INTC_NUMBER 122u

/* UART_INTERRUPT */
#define UART_INTERRUPT__INTC_CORTEXM4_ASSIGNED 1
#define UART_INTERRUPT__INTC_CORTEXM4_PRIORITY 7u
#define UART_INTERRUPT__INTC_NUMBER 46u
#define UART_INTERRUPT_INTC_CORTEXM4_ASSIGNED 1
#define UART_INTERRUPT_INTC_CORTEXM4_PRIORITY 7u
#define UART_INTERRUPT_INTC_NUMBER 46u

/* DETECTOR_ADC_IRQ */
#define DETECTOR_ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define DETECTOR_ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define DETECTOR_ADC_IRQ__INTC_NUMBER 138u
#define DETECTOR_ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define DETECTOR_ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define DETECTOR_ADC_IRQ_INTC_NUMBER 138u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
